import {
  BarChart3,
  Battery,
  Bell,
  Bot,
  Brain,
  Briefcase,
  Calendar,
  Car,
  CheckCircle2,
  CircleDot,
  Clock,
  Droplet,
  FileText,
  Filter,
  Flame,
  Gauge,
  Gift,
  Heart,
  History,
  LayoutGrid,
  LayoutTemplate,
  Megaphone,
  Mic,
  Moon,
  Palette,
  PanelsTopLeft,
  Rocket,
  Search,
  Shield,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Target,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/** String → icon map so showcase content stays pure data. */
export const SHOWCASE_ICONS: Record<string, LucideIcon> = {
  palette: Palette,
  feed: LayoutGrid,
  calendar: Calendar,
  sparkles: Sparkles,
  chart: BarChart3,
  portal: PanelsTopLeft,
  layout: LayoutTemplate,
  target: Target,
  cart: ShoppingCart,
  search: Search,
  moon: Moon,
  rocket: Rocket,
  phone: Smartphone,
  briefcase: Briefcase,
  bell: Bell,
  wifi: Wifi,
  store: Store,
  zap: Zap,
  car: Car,
  wrench: Wrench,
  shield: Shield,
  history: History,
  gauge: Gauge,
  bot: Bot,
  mic: Mic,
  funnel: Filter,
  megaphone: Megaphone,
  heart: Heart,
  brain: Brain,
  file: FileText,
  clock: Clock,
  check: CheckCircle2,
  flame: Flame,
  star: Star,
  gift: Gift,
  droplet: Droplet,
  disc: CircleDot,
  battery: Battery,
};

export function ShowcaseIcon({ name, className, color }: { name: string; className?: string; color?: string }) {
  const Icon = SHOWCASE_ICONS[name] ?? Sparkles;
  return <Icon className={className} style={color ? { color } : undefined} aria-hidden />;
}
